@Library('opus-lib') import br.com.opussoftware.*

pipeline {
	agent any
	options {
		disableConcurrentBuilds()
	}
	stages {
		stage('Git Sync'){
			when { branch 'master' }
			steps{	
				build job: "/oob-git-sync"
			}
		}
		stage('Integration Schema Replication') {
			when { anyOf { branch 'develop'; branch 'develop-mnt' } }
			steps{
				script{
					branchName = "${BRANCH_NAME}"
				}
				build job: "/oob-schema-replication", parameters: [
					string(name: 'gitBranch', value: branchName)
				]
			}
		}
	}
}